DROP TABLE IF EXISTS "HistorialClasificacion";
DROP TABLE IF EXISTS "CompromisoPago";
DROP TABLE IF EXISTS "Notificacion";
DROP TABLE IF EXISTS "Pago";
DROP TABLE IF EXISTS "Cliente";
DROP TABLE IF EXISTS "Cartera";
DROP TABLE IF EXISTS "PlantillaMensaje";
DROP TABLE IF EXISTS "LogAcceso";
DROP TABLE IF EXISTS "Auditoria";
DROP TABLE IF EXISTS "Usuario";

DROP TABLE IF EXISTS "Clasificacion";
DROP TABLE IF EXISTS "CategoriaEmpresa";
DROP TABLE IF EXISTS "Servicio";
DROP TABLE IF EXISTS "Rol";
DROP TABLE IF EXISTS "TipoNotificacion";
DROP TABLE IF EXISTS "CronogramaSunat";
DROP TABLE IF EXISTS "Banco";

CREATE TABLE "Clasificacion" (
  "IdClasificacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Codigo" CHAR(1) UNIQUE NOT NULL,
  "Descripcion" VARCHAR(50) NOT NULL,
  "Color" VARCHAR(20) NOT NULL
);

CREATE TABLE "CategoriaEmpresa" (
  "IdCategoriaEmpresa" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" VARCHAR(20) UNIQUE NOT NULL,
  "Descripcion" VARCHAR(100)
);

CREATE TABLE "Banco" (
  "IdBanco" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE "Servicio" (
  "IdServicio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" VARCHAR(50) UNIQUE NOT NULL,
  "Descripcion" VARCHAR(100)
);

CREATE TABLE "Rol" (
  "IdRol" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" VARCHAR(30) UNIQUE NOT NULL,
  "Descripcion" VARCHAR(100)
);

CREATE TABLE "TipoNotificacion" (
  "IdTipoNotificacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" VARCHAR(20) UNIQUE NOT NULL,
  "Descripcion" VARCHAR(100)
);

CREATE TABLE "CronogramaSunat" (
  "UltimoDigito" SMALLINT,
  "Anio" SMALLINT,
  "FechaVencimiento" DATE,
  PRIMARY KEY ("UltimoDigito", "Anio")
);

CREATE TABLE "PlantillaMensaje" (
  "IdPlantillaMensaje" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdClasificacion" INTEGER UNIQUE,
  "Nombre" VARCHAR(50) NOT NULL,
  "Contenido" TEXT NOT NULL
);

CREATE TABLE "Usuario" (
  "IdUsuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NombreCompleto" VARCHAR(100) NOT NULL,
  "Username" VARCHAR(50) UNIQUE NOT NULL,
  "HashContrasena" VARCHAR(255) NOT NULL,
  "IdRol" INTEGER,
  "Estado" VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
  "Email" VARCHAR(100),
  "FechaCreacion" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "FechaUltimaSesion" TIMESTAMP
);

CREATE TABLE "Cartera" (
  "IdCartera" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" VARCHAR(50) NOT NULL,
  "IdEncargado" INTEGER,
  "FechaCreacion" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "Estado" VARCHAR(10) NOT NULL DEFAULT 'ACTIVA'
);

CREATE TABLE "Cliente" (
  "IdCliente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "RazonSocial" VARCHAR(100) NOT NULL,
  "NombreContacto" VARCHAR(100),
  "RucDni" VARCHAR(11) UNIQUE NOT NULL,
  "UltimoDigitoRUC" SMALLINT,
  "IdClasificacion" INTEGER,
  "IdCartera" SMALLINT,
  "IdEncargado" INTEGER,
  "IdServicio" INTEGER,
  "MontoFijoMensual" DECIMAL(12,2) NOT NULL DEFAULT 0,
  "AplicaMontoFijo" BOOLEAN NOT NULL DEFAULT FALSE,
  "IdCategoriaEmpresa" INTEGER,
  "FechaRegistro" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "FechaVencimiento" DATE,
  "Email" VARCHAR(100),
  "Telefono" VARCHAR(20)
);

CREATE TABLE "Pago" (
  "IdPago" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdCliente" INTEGER,
  "Fecha" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "IdBanco" INTEGER,
  "Monto" DECIMAL(12,2) NOT NULL,
  "Concepto" VARCHAR(100) NOT NULL,
  "MedioPago" VARCHAR(20) NOT NULL,
  "UrlComprobante" VARCHAR(255),
  "MesServicio" DATE NOT NULL,
  "Estado" VARCHAR(10) NOT NULL DEFAULT 'PENDIENTE'
);

CREATE TABLE "Notificacion" (
  "IdNotificacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdCliente" INTEGER,
  "FechaEnvio" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "IdTipoNotificacion" INTEGER,
  "Contenido" TEXT NOT NULL,
  "IdResponsable" INTEGER,
  "Estado" VARCHAR(10) NOT NULL DEFAULT 'PENDIENTE'
);

CREATE TABLE "CompromisoPago" (
  "IdCompromisoPago" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdCliente" INTEGER,
  "FechaCompromiso" DATE NOT NULL,
  "MontoCompromiso" DECIMAL(12,2) NOT NULL,
  "FechaRegistro" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "IdResponsable" INTEGER,
  "Estado" VARCHAR(10) NOT NULL DEFAULT 'PENDIENTE',
  "Observaciones" TEXT
);

CREATE TABLE "HistorialClasificacion" (
  "IdHistorial" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdCliente" INTEGER,
  "IdClasificacionAnterior" INTEGER,
  "IdClasificacionNueva" INTEGER,
  "FechaCambio" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "IdResponsable" INTEGER
);

CREATE TABLE "Auditoria" (
  "IdAuditoria" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NombreTabla" VARCHAR(50) NOT NULL,
  "TipoOperacion" VARCHAR(10) NOT NULL,
  "IdRegistro" INTEGER NOT NULL,
  "Fecha" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "IdUsuario" INTEGER,
  "Detalle" TEXT
);

CREATE TABLE "LogAcceso" (
  "IdLogAcceso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdUsuario" INTEGER,
  "FechaIngreso" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "IP" VARCHAR(45) NOT NULL,
  "Estado" VARCHAR(10) NOT NULL DEFAULT 'OK'
);

-- FOREIGN KEYS
ALTER TABLE "PlantillaMensaje" ADD FOREIGN KEY ("IdClasificacion") REFERENCES "Clasificacion" ("IdClasificacion");

ALTER TABLE "Usuario" ADD FOREIGN KEY ("IdRol") REFERENCES "Rol" ("IdRol");

ALTER TABLE "Cartera" ADD FOREIGN KEY ("IdEncargado") REFERENCES "Usuario" ("IdUsuario");

ALTER TABLE "Cliente" ADD FOREIGN KEY ("IdClasificacion") REFERENCES "Clasificacion" ("IdClasificacion");
ALTER TABLE "Cliente" ADD FOREIGN KEY ("IdCartera") REFERENCES "Cartera" ("IdCartera");
ALTER TABLE "Cliente" ADD FOREIGN KEY ("IdEncargado") REFERENCES "Usuario" ("IdUsuario");
ALTER TABLE "Cliente" ADD FOREIGN KEY ("IdServicio") REFERENCES "Servicio" ("IdServicio");
ALTER TABLE "Cliente" ADD FOREIGN KEY ("IdCategoriaEmpresa") REFERENCES "CategoriaEmpresa" ("IdCategoriaEmpresa");

ALTER TABLE "Pago" ADD FOREIGN KEY ("IdCliente") REFERENCES "Cliente" ("IdCliente");
ALTER TABLE "Pago" ADD FOREIGN KEY ("IdBanco") REFERENCES "Banco" ("IdBanco");

ALTER TABLE "Notificacion" ADD FOREIGN KEY ("IdCliente") REFERENCES "Cliente" ("IdCliente");
ALTER TABLE "Notificacion" ADD FOREIGN KEY ("IdTipoNotificacion") REFERENCES "TipoNotificacion" ("IdTipoNotificacion");
ALTER TABLE "Notificacion" ADD FOREIGN KEY ("IdResponsable") REFERENCES "Usuario" ("IdUsuario");

ALTER TABLE "CompromisoPago" ADD FOREIGN KEY ("IdCliente") REFERENCES "Cliente" ("IdCliente");
ALTER TABLE "CompromisoPago" ADD FOREIGN KEY ("IdResponsable") REFERENCES "Usuario" ("IdUsuario");

ALTER TABLE "HistorialClasificacion" ADD FOREIGN KEY ("IdCliente") REFERENCES "Cliente" ("IdCliente");
ALTER TABLE "HistorialClasificacion" ADD FOREIGN KEY ("IdClasificacionAnterior") REFERENCES "Clasificacion" ("IdClasificacion");
ALTER TABLE "HistorialClasificacion" ADD FOREIGN KEY ("IdClasificacionNueva") REFERENCES "Clasificacion" ("IdClasificacion");
ALTER TABLE "HistorialClasificacion" ADD FOREIGN KEY ("IdResponsable") REFERENCES "Usuario" ("IdUsuario");

ALTER TABLE "Auditoria" ADD FOREIGN KEY ("IdUsuario") REFERENCES "Usuario" ("IdUsuario");

ALTER TABLE "LogAcceso" ADD FOREIGN KEY ("IdUsuario") REFERENCES "Usuario" ("IdUsuario");
