-- Tabla para el detalle de servicios pagados (RF17)
CREATE TABLE IF NOT EXISTS "DetallePagoServicio" (
  "IdDetalle" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "IdPago" INTEGER NOT NULL,
  "MesServicio" DATE NOT NULL,
  "Servicio" VARCHAR(100) NOT NULL,
  "Monto" DECIMAL(12,2) NOT NULL,
  "FechaRegistro" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Foreign key
ALTER TABLE "DetallePagoServicio" ADD FOREIGN KEY ("IdPago") REFERENCES "Pago" ("IdPago");

-- Agregar campo de observaciones a la tabla Pago
ALTER TABLE "Pago" ADD COLUMN IF NOT EXISTS "Observaciones" TEXT;
